### ISSUE TITLE
Support for Rails console

### ISSUE THREAD

**Issue by jasonjho** [GoogleCloudPlatform/appengine-ruby#12]
Looks like tasks and exec commands are meant to support only synchronous operations. Are there any plans to allow a long-running remote Rails console using the same mechanisms under the hood?

**Comment by dazuma** [comment]
@jasonjho Not immediately. This was meant for ad-hoc "build" or "maintenance" tasks against production, the canonical example being database migrations. We deemed it important for such tasks to be logged and tracked, so under the hood it is using the [container build service](https://cloud.google.com/container-builder/) which gives you such facilities.

If you want to open an interactive production console, you can consider using [Cloud Shell](https://cloud.google.com/shell/), or you can simply [ssh into a running container](https://cloud.google.com/appengine/docs/flexible/ruby/debugging-an-instance). It should go without saying, of course, that running a Rails console against a live system can be very dangerous and comes with lots of caveats. The exec facilities of this gem were actually specifically written to give users a safer alternative.
