### ISSUE TITLE
Dependencies not installed by bundler

### ISSUE THREAD

**Issue by thagomizer** [GoogleCloudPlatform/appengine-ruby#17]
My Gemfile has this
```
group :production do
  gem 'appengine'
end
```

I run `bundle install` and everything is installed. Then I run `rake` and I get this error:

```
Could not find google-cloud-debugger-0.32.0 in any of the sources
```

Rake exits telling me to run bundle install for missing gems.

This is on my development machine. I tried eliminating the "group production" and just having it flat in the Gemfile and it didn't fix the issue.

Ruby version: ruby 2.3.3p222
Rails version: 5.2
Bundler version: 1.16.2

**Comment by dazuma** [comment]
This is quite old (and I'm assuming no longer relevant) and most likely unrelated to the appengine gem anyway. I'm going to close it. (@thagomizer you can talk to me in person if this is still relevant to you.)
