### ISSUE TITLE
Missing container image from gcloud app versions describe VERSION

### ISSUE THREAD

**Issue by laertispappas** [GoogleCloudPlatform/appengine-ruby#33]
Hello, 

I'm new to gcloud and trying to set up a rails app based on the docs. I'm not sure if this is a `appengine-ruby` probably not since the gcloud CLI is giving the same results. Not sure where I messed up but when I run

 ```
bundle exec rake appengine:exec -- bundle exec rake db:migrate
```

I get the following error

```
rake aborted!
NoMethodError: undefined method `[]' for nil:NilClass
/Users/laerti.papa/.rvm/gems/ruby-2.6.3/gems/appengine-0.5.0/lib/appengine/exec.rb:754:in `start_build_strategy'
/Users/laerti.papa/.rvm/gems/ruby-2.6.3/gems/appengine-0.5.0/lib/appengine/exec.rb:491:in `start'
/Users/laerti.papa/.rvm/gems/ruby-2.6.3/gems/appengine-0.5.0/lib/appengine/tasks.rb:317:in `start_and_report_errors'
/Users/laerti.pap
```

I debugged a bit and I saw that apparently the app_info hash is missing the `["deployment"]["container"]["image"]`: https://github.com/GoogleCloudPlatform/appengine-ruby/blob/master/lib/appengine/exec.rb#L754 

Running the `deployment` strategy I have other issues but for now I try to understand why `cloud_build` does not work or why the image is not there when I run describe app version.

Any help would be much appreciated. Thank you.

**Comment by dazuma** [comment]
First, is your app in the flexible or standard environment? (Is there `env: flex` in your `app.yaml` or not?)

The `cloud_build` strategy does not work in the standard environment, because App Engine does not provide the image for standard environment apps.

**Comment by laertispappas** [comment]
Hi @dazuma  my app is running in the flex. environment. This command for some reason does not give me the container image in the JSON output:

```
gcloud app versions describe 20200415t004447
```

I ended app getting a shell in a running version and running the migrations manually from there. But I need to automate this.

**Comment by jerelmiller** [comment]
I have also encountered this running in a flex environment.

**Comment by jonasmora** [comment]
Is there any update on this issue?

**Comment by asanchez0527** [comment]
I'm also facing this issue, is there any workaround?

**Comment by jonasmora** [comment]
Now I'm getting this error with a flex environment, is there any update?

**Comment by dwalker11** [comment]
Any update?

**Comment by dazuma** [comment]
I just had a conversation with one of the App Engine engineers, and it looks like there's a change to the behavior of the Flexible Environment that's causing this. They suggested a workaround that I'm now working on implementing. Apparently the change is one that's been planned for a while and should make the build process more reliable, but the rollout has been slow which is why it's been hard to reproduce and diagnose.

**Comment by dazuma** [comment]
The fix is scheduled for release Wed Dec 2.
