### ISSUE TITLE
Is this actively maintained?

### ISSUE THREAD

**Issue by laurawadden** [GoogleCloudPlatform/appengine-ruby#37]
Hello appengine-ruby team,
I'm trying to evaluate whether I will implement this gem in my project and see the last commit was 17 months ago.
Could someone from the maintainers team give me an idea if this is actively maintained? It seems not to be.
Thank you!
Best,
Laura

**Comment by dazuma** [comment]
Hi, yes this is being maintained. We're in fact working on a fix right now in response to some changes that are happening to the Flexible Environment build process.
